title: "DAB - Détention Autonome Bitcoin"
description: "Démocratiser l'accès à la souveraineté financière à travers Bitcoin, en français"
url: "https://dab-bitcoin.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

author:
  name: "Alexandre Boudreau"
  bio: "Passionné de Bitcoin et de souveraineté financière"
  email: "dab-bitcoin@proton.me"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

markdown: kramdown
search: true
